### ISSUE TITLE
true всегда true)

### ISSUE THREAD

**Issue by rubyjiun** [KaterinaSav/ruby_first_game#2]
https://github.com/KaterinaSav/ruby_first_game/blob/master/main.rb#L69
https://github.com/KaterinaSav/ruby_first_game/blob/master/main.rb#L22
и т.д.
```ruby
def update
  if @player && @space && @player.step==true
    player_attack
  end
  if @player && @mobs && @player.step == false
    mobs_attack
  end      
end
```
Может стоит изменить на:
```ruby
def update
  if @player && @space && @player.step
    player_attack
  end
  if @player && @mobs && !@player.step
    mobs_attack
  end      
end
```
или
```ruby
def update
  player_attack if @player && @space && @player.step
  mobs_attack if @player && @mobs && !@player.step
end
```
или elsif

просмотри эту ошибку во всём проекте)

**Comment by KaterinaSav** [comment]
в этой строке оставила проверку

    mobs_attack if @player && @mobs && @player.step==false

т.к. методы player_attack и mobs_attack выполняются поочередно,  step определяет чья очередь. 
mobs_attack выполняется когда step ==false
