### ISSUE TITLE
.rvmrc

### ISSUE THREAD

**Issue by rubyjiun** [KaterinaSav/ruby_first_game#3]
как я могу узнать, какая версия руби использовалась для создания проекта?

**Comment by KaterinaSav** [comment]
добавила в readme

**Comment by rubyjiun** [comment]
просмотри новый документ в Day 0

**Comment by KaterinaSav** [comment]
а, понятно. сделала)

**Comment by rubyjiun** [comment]
также встречаются .ruby-version, .ruby-gemset
