### ISSUE TITLE
.hound.yml 

### ISSUE THREAD

**Issue by rubyjiun** [KaterinaSav/ruby_first_game#4]
Надо использовать.

**Comment by rubyjiun** [comment]
@KaterinaSav просмотри плиз https://github.com/KaterinaSav/sample_app/issues/9

**Comment by rubyjiun** [comment]
Подключила houndci это хорошо, но нужно заюзать... и отрефакторить.

**Comment by KaterinaSav** [comment]
@rubyjiun а hound используется только в pull реквестах или можно еще как-то проверить свой код?

**Comment by rubyjiun** [comment]
@KaterinaSav hound испозуется только в пул реквестах...
hound - сам по себе ничего не умеет кроме, как выставлять комментарии, всё остальное делают за него старонние гемы https://houndci.com/configuration (RuboCop, coffeelint,  JSHint, SCSS-Lint).

Ты конечно можешь их всех заюзать, но не стоит)
Тебе нужно создать умный pull request)

**Comment by rubyjiun** [comment]
https://github.com/KaterinaSav/ruby_first_game/pull/10
